# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_mpu.parallel.ipynb.

# %% auto 0
__all__ = ['BackendType', 'ParallelState']

# %% ../../nbs/02_mpu.parallel.ipynb 4
from typing import Literal

# %% ../../nbs/02_mpu.parallel.ipynb 5
BackendType = Literal["nccl", "gloo", "mpi"]

# %% ../../nbs/02_mpu.parallel.ipynb 6
class ParallelState:
    def __init__(
        self,
        tensor_parallel_size: int,
        pipeline_parallel_size: int,
        data_parallel_size: int,
        world_size: int,
        master_addr: str,
        master_port: int,
        backend: BackendType
    ):
        self.tensor_parallel_size = tensor_parallel_size
        self.pipeline_parallel_size = pipeline_parallel_size
        self.data_parallel_size = data_parallel_size
        self.world_size = world_size
        self.master_addr = master_addr
        self.master_port = master_port
        self.backend = backend
    
    @property
    def rank(self):
        return 1
