# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastgoose',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/fastgoose',
                'lib_path': 'fastgoose'},
  'syms': {'fastgoose.core': {'fastgoose.core.foo': ('core.html#foo', 'fastgoose/core.py')}, 'fastgoose.optim.zero': {}}}
